import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiRequest } from "@/shared/lib/apiClient";
import { useAuth } from "@/features/auth";
import { useLanguage } from "@/app/providers/LanguageProvider";
import { logger } from "@/shared/services/logger";
import { Bell, Loader2 } from "lucide-react";
import { ROUTES } from "@/shared/config/routes";

interface FeedItem {
  id: string;
  template: string;
  title: string;
  body: string;
  payload: Record<string, unknown> | null;
  readAt: string | null;
  createdAt: string;
}

const POLL_MS = 60_000;

/**
 * In-app notification feed. The unread count refreshes on open and on a
 * slow interval — notifications are generated by a background sweep the
 * browser has no other signal for, so this is a deliberate poll rather
 * than a substitute for the SSE streams used elsewhere.
 */
export function NotificationBell() {
  const { user } = useAuth();
  const { language } = useLanguage();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [items, setItems] = useState<FeedItem[]>([]);
  const [unread, setUnread] = useState(0);
  const [loading, setLoading] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);

  const refreshCount = useCallback(async () => {
    if (!user) return;
    try {
      const res = await apiRequest<{ unreadCount: number }>("/notifications/unread-count");
      setUnread(res.unreadCount);
    } catch (err) {
      logger.debug?.("Notification count unavailable", err);
    }
  }, [user]);

  useEffect(() => {
    if (!user) {
      setUnread(0);
      setItems([]);
      return;
    }
    void refreshCount();
    const timer = setInterval(refreshCount, POLL_MS);
    return () => clearInterval(timer);
  }, [user, refreshCount]);

  useEffect(() => {
    const onClickOutside = (e: MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, []);

  const openFeed = async () => {
    const next = !open;
    setOpen(next);
    if (!next) return;

    setLoading(true);
    try {
      const res = await apiRequest<{ items: FeedItem[]; unreadCount: number }>("/notifications?limit=20");
      setItems(res.items);
      setUnread(res.unreadCount);
    } catch (err) {
      logger.error("Failed to load notifications:", err);
    } finally {
      setLoading(false);
    }
  };

  const markAllRead = async () => {
    try {
      const res = await apiRequest<{ unreadCount: number }>("/notifications/read", {
        method: "POST",
        body: {},
      });
      setUnread(res.unreadCount);
      setItems((prev) => prev.map((i) => ({ ...i, readAt: new Date().toISOString() })));
    } catch (err) {
      logger.error("Failed to mark notifications read:", err);
    }
  };

  const handleItemClick = async (item: FeedItem) => {
    setOpen(false);
    if (!item.readAt) {
      setItems((prev) =>
        prev.map((i) => (i.id === item.id ? { ...i, readAt: new Date().toISOString() } : i))
      );
      setUnread((prev) => Math.max(0, prev - 1));
      try {
        await apiRequest("/notifications/read", { method: "POST", body: { ids: [item.id] } });
      } catch (err) {
        logger.error("Failed to mark notification read:", err);
      }
    }
    const issueId = item.payload?.issueId;
    if (typeof issueId === "string" && issueId) {
      navigate(ROUTES.ISSUE_DETAIL.replace(":id", issueId));
    }
  };

  if (!user) return null;

  return (
    <div ref={panelRef} className="relative">
      <button
        onClick={openFeed}
        aria-label={language === "en" ? "Notifications" : "सूचनाएं"}
        className="relative p-2 rounded-lg hover:bg-muted transition-colors"
      >
        <Bell className="w-4 h-4 text-muted-foreground" />
        {unread > 0 && (
          <span className="absolute -top-0.5 -right-0.5 min-w-[16px] h-4 px-1 rounded-full bg-destructive text-destructive-foreground text-[9px] font-bold flex items-center justify-center">
            {unread > 99 ? "99+" : unread}
          </span>
        )}
      </button>

      {open && (
        // Anchoring to the button's own edge overflows off-screen on narrow
        // viewports where the button isn't flush with the viewport edge —
        // pin to the viewport itself below sm, anchor to the button above it.
        <div className="fixed left-3 right-3 top-16 sm:absolute sm:left-auto sm:right-0 sm:top-auto sm:mt-2 sm:w-80 max-h-96 overflow-y-auto bg-card border border-border rounded-xl shadow-2xl z-[1100]">
          <div className="flex items-center justify-between px-3 py-2 border-b border-border sticky top-0 bg-card">
            <span className="text-xs font-bold text-foreground">
              {language === "en" ? "Notifications" : "सूचनाएं"}
            </span>
            {unread > 0 && (
              <button onClick={markAllRead} className="text-[10px] text-primary hover:underline">
                {language === "en" ? "Mark all read" : "सभी पढ़ा हुआ"}
              </button>
            )}
          </div>

          {loading ? (
            <div className="flex items-center justify-center py-6">
              <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
            </div>
          ) : items.length === 0 ? (
            <p className="text-xs text-muted-foreground text-center py-6">
              {language === "en" ? "Nothing yet." : "अभी कुछ नहीं।"}
            </p>
          ) : (
            <ul className="divide-y divide-border/60">
              {items.map((n) => (
                <li key={n.id}>
                  <button
                    type="button"
                    onClick={() => handleItemClick(n)}
                    className={`w-full text-left px-3 py-2 hover:bg-muted/60 transition-colors ${n.readAt ? "" : "bg-primary/5"}`}
                  >
                    <p className="text-xs font-semibold text-foreground">{n.title}</p>
                    <p className="text-[11px] text-muted-foreground mt-0.5">{n.body}</p>
                    <p className="text-[10px] text-muted-foreground/70 mt-1">
                      {new Date(n.createdAt).toLocaleString()}
                    </p>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
